**Customer Level Features**

In [3]:
import pandas as pd
import numpy as np

In [4]:
file_path = r"D:\nava-ai\data\clean\retail_buisness_cleaned_data.xlsx"
df_clean = pd.read_excel(file_path)
df_clean.head(10)

,invoice,stockcode,description,quantity,invoicedate,price,customer_id,sales_revenue,return_amount,net_revenue,...,country_Thailand,country_USA,country_United Arab Emirates,country_United Kingdom,country_Unspecified,country_West Indies,transaction_type_Return/Cancel,transaction_type_Sale,price_status_Invalid/Adjustment Price,price_status_Valid Price
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,83.4,0.0,83.4,...,0,0,0,1,0,0,0,1,0,1
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,81.0,0.0,81.0,...,0,0,0,1,0,0,0,1,0,1
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,81.0,0.0,81.0,...,0,0,0,1,0,0,0,1,0,1
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,100.8,0.0,100.8,...,0,0,0,1,0,0,0,1,0,1
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,30.0,0.0,30.0,...,0,0,0,1,0,0,0,1,0,1
5,489434,22064,PINK DOUGHNUT TRINKET POT,24,2009-12-01 07:45:00,1.65,13085.0,39.6,0.0,39.6,...,0,0,0,1,0,0,0,1,0,1
6,489434,21871,SAVE THE PLANET MUG,24,2009-12-01 07:45:00,1.25,13085.0,30.0,0.0,30.0,...,0,0,0,1,0,0,0,1,0,1
7,489434,21523,FANCY FONT HOME SWEET HOME DOORMAT,10,2009-12-01 07:45:00,5.95,13085.0,59.5,0.0,59.5,...,0,0,0,1,0,0,0,1,0,1
8,489435,22350,CAT BOWL,12,2009-12-01 07:46:00,2.55,13085.0,30.6,0.0,30.6,...,0,0,0,1,0,0,0,1,0,1
9,489435,22349,"DOG BOWL , CHASING BALL DESIGN",12,2009-12-01 07:46:00,3.75,13085.0,45.0,0.0,45.0,...,0,0,0,1,0,0,0,1,0,1

In [5]:
customer_features = df_clean.groupby("customer_id").agg(
    total_orders=("invoice", "nunique")
).reset_index()

In [7]:
customer_features.head()

   customer_id  total_orders
0      12346.0            15
1      12347.0             2
2      12348.0             1
3      12349.0             4
4      12351.0             1

In [8]:
customer_features = customer_features.merge(
    df_clean.groupby("customer_id")["quantity"].sum().reset_index(
        name= "total_quantity"
    ),
    on="customer_id",
    how="left"
)

In [9]:
customer_features.head()

   customer_id  total_orders  total_quantity
0      12346.0            15              53
1      12347.0             2             828
2      12348.0             1             373
3      12349.0             4             988
4      12351.0             1             261

In [10]:
customer_features = customer_features.merge(
    df_clean.groupby("customer_id")["sales_revenue"].sum().reset_index(
        name= "total_sales"
    ),
    on="customer_id",
    how="left"
)

In [11]:
customer_features.head()

   customer_id  total_orders  total_quantity  total_sales
0      12346.0            15              53       372.86
1      12347.0             2             828      1323.32
2      12348.0             1             373       222.16
3      12349.0             4             988      2671.14
4      12351.0             1             261       300.93

In [14]:
customer_features = customer_features.merge(
    df_clean.groupby("customer_id")["return_amount"].sum().reset_index(
        name= "total_return_amount"
    ),
    on="customer_id",
    how="left"
)

In [15]:
customer_features.head()

,customer_id,total_orders,total_quantity,total_sales,total_return,total_return_amount
0,12346.0,15,53,372.86,424.60,424.60
1,12347.0,2,828,1323.32,0.00,0.00
2,12348.0,1,373,222.16,0.00,0.00
3,12349.0,4,988,2671.14,24.15,24.15
4,12351.0,1,261,300.93,0.00,0.00

In [16]:
customer_features = customer_features.merge(
    df_clean.groupby("customer_id")["net_revenue"].sum().reset_index(
        name= "net_revenue"
    ),
    on="customer_id",
    how="left"
)

In [17]:
customer_features.head()

,customer_id,total_orders,total_quantity,total_sales,total_return,total_return_amount,net_revenue
0,12346.0,15,53,372.86,424.60,424.60,-51.74
1,12347.0,2,828,1323.32,0.00,0.00,1323.32
2,12348.0,1,373,222.16,0.00,0.00,222.16
3,12349.0,4,988,2671.14,24.15,24.15,2646.99
4,12351.0,1,261,300.93,0.00,0.00,300.93

In [23]:
customer_features["avg_oreder_value"] = (
    customer_features["total_sales"] /
    customer_features["total_orders"]
)

In [24]:
customer_features.head()

,customer_id,total_orders,total_quantity,total_sales,total_return,total_return_amount,net_revenue,avg_oreder_value
0,12346.0,15,53,372.86,424.60,424.60,-51.74,24.857333
1,12347.0,2,828,1323.32,0.00,0.00,1323.32,661.660000
2,12348.0,1,373,222.16,0.00,0.00,222.16,222.160000
3,12349.0,4,988,2671.14,24.15,24.15,2646.99,667.785000
4,12351.0,1,261,300.93,0.00,0.00,300.93,300.930000

In [27]:
customer_features = customer_features.merge(
    df_clean.groupby("customer_id")["invoicedate"].min().reset_index(
        name="first_purchase_date"
    )
    ,
    on="customer_id",
    how="left"
)

In [29]:
customer_features = customer_features.merge(
    df_clean.groupby("customer_id")["invoicedate"].max().reset_index(
        name = "last_purchase_date"
    ),
    on="customer_id",
    how="left"
)

In [30]:
customer_features.head()

,customer_id,total_orders,total_quantity,total_sales,total_return,total_return_amount,net_revenue,avg_oreder_value,first_purchase_date,last_purchase_date
0,12346.0,15,53,372.86,424.60,424.60,-51.74,24.857333,2009-12-14 08:34:00,2010-10-04 16:33:00
1,12347.0,2,828,1323.32,0.00,0.00,1323.32,661.660000,2010-10-31 14:20:00,2010-12-07 14:57:00
2,12348.0,1,373,222.16,0.00,0.00,222.16,222.160000,2010-09-27 14:59:00,2010-09-27 14:59:00
3,12349.0,4,988,2671.14,24.15,24.15,2646.99,667.785000,2009-12-04 12:49:00,2010-10-28 08:23:00
4,12351.0,1,261,300.93,0.00,0.00,300.93,300.930000,2010-11-29 15:23:00,2010-11-29 15:23:00

In [31]:
customer_features = customer_features.merge(
    df_clean.groupby("customer_id")["stockcode"].nunique().reset_index(
        name = "unique_product_purchased"
    ),
    on = "customer_id",
    how = "left"
)

In [33]:
customer_features.head()

,customer_id,total_orders,total_quantity,total_sales,total_return,total_return_amount,net_revenue,avg_oreder_value,first_purchase_date,last_purchase_date,unique_product_purchased
0,12346.0,15,53,372.86,424.60,424.60,-51.74,24.857333,2009-12-14 08:34:00,2010-10-04 16:33:00,29
1,12347.0,2,828,1323.32,0.00,0.00,1323.32,661.660000,2010-10-31 14:20:00,2010-12-07 14:57:00,70
2,12348.0,1,373,222.16,0.00,0.00,222.16,222.160000,2010-09-27 14:59:00,2010-09-27 14:59:00,20
3,12349.0,4,988,2671.14,24.15,24.15,2646.99,667.785000,2009-12-04 12:49:00,2010-10-28 08:23:00,92
4,12351.0,1,261,300.93,0.00,0.00,300.93,300.930000,2010-11-29 15:23:00,2010-11-29 15:23:00,21

In [36]:
customer_features["number_of_active_days"] = (customer_features["last_purchase_date"] - customer_features["first_purchase_date"]).dt.days

In [37]:
customer_features.head()

,customer_id,total_orders,total_quantity,total_sales,total_return,total_return_amount,net_revenue,avg_oreder_value,first_purchase_date,last_purchase_date,unique_product_purchased,number_of_active_days
0,12346.0,15,53,372.86,424.60,424.60,-51.74,24.857333,2009-12-14 08:34:00,2010-10-04 16:33:00,29,294
1,12347.0,2,828,1323.32,0.00,0.00,1323.32,661.660000,2010-10-31 14:20:00,2010-12-07 14:57:00,70,37
2,12348.0,1,373,222.16,0.00,0.00,222.16,222.160000,2010-09-27 14:59:00,2010-09-27 14:59:00,20,0
3,12349.0,4,988,2671.14,24.15,24.15,2646.99,667.785000,2009-12-04 12:49:00,2010-10-28 08:23:00,92,327
4,12351.0,1,261,300.93,0.00,0.00,300.93,300.930000,2010-11-29 15:23:00,2010-11-29 15:23:00,21,0

In [38]:
reference_date = df_clean["invoicedate"].max()

In [39]:
customer_features["recency_days"] = (reference_date - customer_features["last_purchase_date"]).dt.days

In [42]:
customer_features[["customer_id","last_purchase_date","recency_days"]].head()

   customer_id  last_purchase_date  recency_days
0      12346.0 2010-10-04 16:33:00            66
1      12347.0 2010-12-07 14:57:00             2
2      12348.0 2010-09-27 14:59:00            73
3      12349.0 2010-10-28 08:23:00            42
4      12351.0 2010-11-29 15:23:00            10

In [43]:
customer_features.to_csv(
    "customer_features.csv",
    index=False
)

In [44]:
customer_features["frequency_score"] = pd.qcut(
    customer_features["total_orders"].rank(method="first"),
    5,
    labels=[1, 2, 3, 4, 5]
).astype(int)

In [45]:
customer_features[["customer_id" , "total_orders" , "frequency_score"]]

      customer_id  total_orders  frequency_score
0         12346.0            15                5
1         12347.0             2                2
2         12348.0             1                1
3         12349.0             4                3
4         12351.0             1                1
...           ...           ...              ...
4378      18283.0             6                4
4379      18284.0             2                3
4380      18285.0             1                2
4381      18286.0             3                3
4382      18287.0             5                4

[4383 rows x 3 columns]

In [46]:
customer_features["recency_score"] = pd.qcut(
    customer_features["recency_days"].rank(method="first"),
    5,
    labels=[5, 4, 3, 2, 1]
).astype(int)

In [47]:
customer_features[
    ["customer_id", "recency_days", "recency_score"]
].head(10)

   customer_id  recency_days  recency_score
0      12346.0            66              3
1      12347.0             2              5
2      12348.0            73              2
3      12349.0            42              3
4      12351.0            10              5
5      12352.0            10              5
6      12353.0            43              3
7      12355.0           202              1
8      12356.0            15              4
9      12357.0            23              4

In [48]:
customer_features["monetary_score"] = pd.qcut(
    customer_features["net_revenue"].rank(method="first"),
    5,
    labels=[1, 2, 3, 4, 5]
).astype(int)

In [49]:
customer_features[
    ["customer_id", "net_revenue", "monetary_score"]
].head(10)

   customer_id  net_revenue  monetary_score
0      12346.0       -51.74               1
1      12347.0      1323.32               4
2      12348.0       222.16               1
3      12349.0      2646.99               5
4      12351.0       300.93               2
5      12352.0       343.80               2
6      12353.0       317.76               2
7      12355.0       488.21               3
8      12356.0      3560.30               5
9      12357.0     12079.99               5

In [50]:
customer_features["rfm_score"] = (
    customer_features["recency_score"].astype(str) +
    customer_features["frequency_score"].astype(str) +
    customer_features["monetary_score"].astype(str)
)

In [51]:
customer_features[
    [
        "customer_id",
        "recency_score",
        "frequency_score",
        "monetary_score",
        "rfm_score"
    ]
].head(10)

   customer_id  recency_score  frequency_score  monetary_score rfm_score
0      12346.0              3                5               1       351
1      12347.0              5                2               4       524
2      12348.0              2                1               1       211
3      12349.0              3                3               5       335
4      12351.0              5                1               2       512
5      12352.0              5                2               2       522
6      12353.0              3                1               2       312
7      12355.0              1                1               3       113
8      12356.0              4                3               5       435
9      12357.0              4                2               5       425

In [54]:
customer_features.to_csv(
    r"D:\nava-ai\data\features\customer_features.csv",
    index=False
)

In [55]:
customer_features.columns.to_list()

['customer_id',
 'total_orders',
 'total_quantity',
 'total_sales',
 'total_return',
 'total_return_amount',
 'net_revenue',
 'avg_oreder_value',
 'first_purchase_date',
 'last_purchase_date',
 'unique_product_purchased',
 'number_of_active_days',
 'recency_days',
 'frequency_score',
 'recency_score',
 'monetary_score',
 'rfm_score']

**Product Level Features**

In [5]:
product_features = df_clean.groupby("stockcode").agg(
    total_orders = ("invoice","nunique")
).reset_index()

In [8]:
product_features.head()

  stockcode  total_orders
0     10002           317
1     10080             6
2     10109             2
3     10120            49
4     10125            81

In [ ]:
product_features = product_features.merge(
    df_clean[df_clean["quantity"] > 0]
    .groupby("stockcode")["quantity"]
    .sum()
    .reset_index(name="total_units_sold"),
    on="stockcode",
    how="left"
)

In [10]:
product_features.head()

  stockcode  total_orders  total_units_sold
0     10002           317            7971.0
1     10080             6             102.0
2     10109             2               4.0
3     10120            49             487.0
4     10125            81             853.0

In [11]:
product_features = product_features.merge(
    df_clean[df_clean["quantity"] < 0]
    .groupby("stockcode")["quantity"]
    .sum()
    .abs()
    .reset_index(name="total_units_returned"),
    on="stockcode",
    how="left"
)

In [12]:
product_features.head()

  stockcode  total_orders  total_units_sold  total_units_returned
0     10002           317            7971.0                1223.0
1     10080             6             102.0                   NaN
2     10109             2               4.0                   4.0
3     10120            49             487.0                9030.0
4     10125            81             853.0                   NaN

In [13]:
product_features = product_features.merge(
    df_clean.groupby("stockcode")["sales_revenue"].sum().reset_index(
        name="total_sales"
    ),
    on="stockcode",
    how="left"
)

In [14]:
product_features.head()

  stockcode  total_orders  total_units_sold  total_units_returned  total_sales
0     10002           317            7971.0                1223.0      6333.76
1     10080             6             102.0                   NaN        10.20
2     10109             2               4.0                   4.0         1.68
3     10120            49             487.0                9030.0       105.57
4     10125            81             853.0                   NaN       761.66

In [15]:
product_features = product_features.merge(
    df_clean.groupby("stockcode")["return_amount"].sum().reset_index(
        name="total_return_amount"
    ),
    on="stockcode",
    how="left"
)

In [16]:
product_features.head()

,stockcode,total_orders,total_units_sold,total_units_returned,total_sales,total_return_amount
0,10002,317,7971.0,1223.0,6333.76,883.55
1,10080,6,102.0,NaN,10.20,0.00
2,10109,2,4.0,4.0,1.68,0.00
3,10120,49,487.0,9030.0,105.57,6.30
4,10125,81,853.0,NaN,761.66,0.00

In [18]:
product_features = product_features.merge(
    df_clean.groupby("stockcode")["net_revenue"].sum().reset_index(
        name="total_net_revenue"
    ),
    on="stockcode",
    how="left"
)

In [19]:
product_features.head()

,stockcode,total_orders,total_units_sold,total_units_returned,total_sales_x,total_return_amount,total_sales_y,total_net_revenue
0,10002,317,7971.0,1223.0,6333.76,883.55,5450.21,5450.21
1,10080,6,102.0,NaN,10.20,0.00,10.20,10.20
2,10109,2,4.0,4.0,1.68,0.00,1.68,1.68
3,10120,49,487.0,9030.0,105.57,6.30,99.27,99.27
4,10125,81,853.0,NaN,761.66,0.00,761.66,761.66

In [21]:
product_features = product_features.merge(
    df_clean.groupby("stockcode")["customer_id"].nunique().reset_index(
        name="unique_customer"
    ),
    on="stockcode",
    how="left"
)

In [22]:
product_features.head()

,stockcode,total_orders,total_units_sold,total_units_returned,total_sales_x,total_return_amount,total_sales_y,total_net_revenue,unique_customer
0,10002,317,7971.0,1223.0,6333.76,883.55,5450.21,5450.21,153
1,10080,6,102.0,NaN,10.20,0.00,10.20,10.20,4
2,10109,2,4.0,4.0,1.68,0.00,1.68,1.68,1
3,10120,49,487.0,9030.0,105.57,6.30,99.27,99.27,33
4,10125,81,853.0,NaN,761.66,0.00,761.66,761.66,50

In [23]:
product_features = product_features.merge(
    df_clean[
        (df_clean["quantity"] > 0) &
        (df_clean["price"] > 0)
    ]
    .groupby("stockcode")["price"]
    .mean()
    .reset_index(name="average_price"),
    on="stockcode",
    how="left"
)

In [24]:
product_features.head()

,stockcode,total_orders,total_units_sold,total_units_returned,total_sales_x,total_return_amount,total_sales_y,total_net_revenue,unique_customer,average_price
0,10002,317,7971.0,1223.0,6333.76,883.55,5450.21,5450.21,153,0.967714
1,10080,6,102.0,NaN,10.20,0.00,10.20,10.20,4,0.850000
2,10109,2,4.0,4.0,1.68,0.00,1.68,1.68,1,0.420000
3,10120,49,487.0,9030.0,105.57,6.30,99.27,99.27,33,0.256809
4,10125,81,853.0,NaN,761.66,0.00,761.66,761.66,50,1.012941

In [25]:
product_features = product_features.merge(
    df_clean[df_clean["quantity"] > 0]
    .groupby("stockcode")["date"]
    .nunique()
    .reset_index(name="active_selling_days"),
    on="stockcode",
    how="left"
)

In [26]:
product_features.head()

,stockcode,total_orders,total_units_sold,total_units_returned,total_sales_x,total_return_amount,total_sales_y,total_net_revenue,unique_customer,average_price,active_selling_days
0,10002,317,7971.0,1223.0,6333.76,883.55,5450.21,5450.21,153,0.967714,187.0
1,10080,6,102.0,NaN,10.20,0.00,10.20,10.20,4,0.850000,6.0
2,10109,2,4.0,4.0,1.68,0.00,1.68,1.68,1,0.420000,1.0
3,10120,49,487.0,9030.0,105.57,6.30,99.27,99.27,33,0.256809,42.0
4,10125,81,853.0,NaN,761.66,0.00,761.66,761.66,50,1.012941,64.0

In [28]:
product_features.to_csv(
    r"D:\nava-ai\data\features/product_features.csv",
    index=False
)

**Time Level features**

In [5]:
time_features = df_clean.groupby("date").agg(
    total_orders = ("invoice" , "nunique")
).reset_index()

In [6]:
time_features.head()

        date  total_orders
0 2009-12-01           166
1 2009-12-02           133
2 2009-12-03           150
3 2009-12-04           107
4 2009-12-05            32

In [7]:
time_features = time_features.merge(
    df_clean[df_clean["quantity"] > 0]
    .groupby("date")["quantity"]
    .sum()
    .reset_index(name="total_units_sold"),
    on="date",
    how="left"
)

In [8]:
time_features.head()

        date  total_orders  total_units_sold
0 2009-12-01           166             26328
1 2009-12-02           133             31846
2 2009-12-03           150             50876
3 2009-12-04           107             21290
4 2009-12-05            32              5119

In [11]:
time_features = time_features.merge(
    df_clean[df_clean["quantity"] < 0]
    .groupby("date")["quantity"]
    .sum()
    .abs()
    .reset_index(name="total_units_returned"),
    on="date",
    how="left"
)

In [12]:
time_features.head()

,date,total_orders,total_units_sold,total_units_returned_x,total_units_returned_y
0,2009-12-01,166,26328,-2412.0,2412.0
1,2009-12-02,133,31846,-1996.0,1996.0
2,2009-12-03,150,50876,-6002.0,6002.0
3,2009-12-04,107,21290,-404.0,404.0
4,2009-12-05,32,5119,-86.0,86.0

In [13]:
time_features = time_features.merge(
    df_clean.groupby("date")["sales_revenue"]
    .sum()
    .reset_index(name="total_sales"),
    on="date",
    how="left"
    
)

In [14]:
time_features.head()

,date,total_orders,total_units_sold,total_units_returned_x,total_units_returned_y,total_sales
0,2009-12-01,166,26328,-2412.0,2412.0,54351.23
1,2009-12-02,133,31846,-1996.0,1996.0,63172.58
2,2009-12-03,150,50876,-6002.0,6002.0,73972.45
3,2009-12-04,107,21290,-404.0,404.0,40582.32
4,2009-12-05,32,5119,-86.0,86.0,9803.05

In [15]:
time_features = time_features.merge(
    df_clean.groupby("date")["return_amount"]
    .sum()
    .reset_index(name="total_return_amount"),
    on="date",
    how="left"
)

In [16]:
time_features.head()

,date,total_orders,total_units_sold,total_units_returned_x,total_units_returned_y,total_sales,total_return_amount
0,2009-12-01,166,26328,-2412.0,2412.0,54351.23,1340.47
1,2009-12-02,133,31846,-1996.0,1996.0,63172.58,588.92
2,2009-12-03,150,50876,-6002.0,6002.0,73972.45,5944.86
3,2009-12-04,107,21290,-404.0,404.0,40582.32,386.52
4,2009-12-05,32,5119,-86.0,86.0,9803.05,0.00

In [17]:
time_features = time_features.merge(
    df_clean.groupby("date")["net_revenue"]
    .sum()
    .reset_index(name="net_revenue"),
    on="date",
    how="left"
)

In [18]:
time_features.head()

,date,total_orders,total_units_sold,total_units_returned_x,total_units_returned_y,total_sales,total_return_amount,net_revenue
0,2009-12-01,166,26328,-2412.0,2412.0,54351.23,1340.47,53010.76
1,2009-12-02,133,31846,-1996.0,1996.0,63172.58,588.92,62583.66
2,2009-12-03,150,50876,-6002.0,6002.0,73972.45,5944.86,68027.59
3,2009-12-04,107,21290,-404.0,404.0,40582.32,386.52,40195.80
4,2009-12-05,32,5119,-86.0,86.0,9803.05,0.00,9803.05

In [19]:
time_features = time_features.merge(
    df_clean.groupby("date")["customer_id"]
    .nunique()
    .reset_index(name="unique_customers"),
    on="date",
    how="left"
)

In [20]:
time_features.head()

,date,total_orders,total_units_sold,total_units_returned_x,total_units_returned_y,total_sales,total_return_amount,net_revenue,unique_customers
0,2009-12-01,166,26328,-2412.0,2412.0,54351.23,1340.47,53010.76,117
1,2009-12-02,133,31846,-1996.0,1996.0,63172.58,588.92,62583.66,98
2,2009-12-03,150,50876,-6002.0,6002.0,73972.45,5944.86,68027.59,116
3,2009-12-04,107,21290,-404.0,404.0,40582.32,386.52,40195.80,82
4,2009-12-05,32,5119,-86.0,86.0,9803.05,0.00,9803.05,26

In [21]:
time_features = time_features.merge(
    df_clean[df_clean["quantity"] > 0]
    .groupby("date")["stockcode"]
    .nunique()
    .reset_index(name="unique_products_sold"),
    on="date",
    how="left"
)

In [22]:
time_features.head()

,date,total_orders,total_units_sold,total_units_returned_x,total_units_returned_y,total_sales,total_return_amount,net_revenue,unique_customers,unique_products_sold
0,2009-12-01,166,26328,-2412.0,2412.0,54351.23,1340.47,53010.76,117,1329
1,2009-12-02,133,31846,-1996.0,1996.0,63172.58,588.92,62583.66,98,1393
2,2009-12-03,150,50876,-6002.0,6002.0,73972.45,5944.86,68027.59,116,1323
3,2009-12-04,107,21290,-404.0,404.0,40582.32,386.52,40195.80,82,1252
4,2009-12-05,32,5119,-86.0,86.0,9803.05,0.00,9803.05,26,285

In [24]:
time_features = time_features.drop(
    columns=["total_units_returned_x"]
)

In [25]:
time_features.head()

,date,total_orders,total_units_sold,total_units_returned_y,total_sales,total_return_amount,net_revenue,unique_customers,unique_products_sold
0,2009-12-01,166,26328,2412.0,54351.23,1340.47,53010.76,117,1329
1,2009-12-02,133,31846,1996.0,63172.58,588.92,62583.66,98,1393
2,2009-12-03,150,50876,6002.0,73972.45,5944.86,68027.59,116,1323
3,2009-12-04,107,21290,404.0,40582.32,386.52,40195.80,82,1252
4,2009-12-05,32,5119,86.0,9803.05,0.00,9803.05,26,285

In [26]:
time_features.to_csv(
    r"D:\nava-ai\data\features\time_features.csv",
    index=False
)